[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edge-deid"
version = "0.3.0"

[tool.setuptools.packages.find]
where = ["src"]
include = ["deid_pipeline*"]
