name: ai_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # -- Python environment
  - python=3.10
  - pip
  - git

  # -- Scientific computing / data processing
  - numpy=1.24.3
  - pandas
  - scipy
  - matplotlib
  - tqdm=4.67.1
  - typing-extensions
  - python-dateutil
  - tzdata

  # -- NLP + text processing
  - spacy>=3.5,<3.6
  - python-docx
  - beautifulsoup4
  - lxml
  - jieba=0.42.1
  - openpyxl
  - xlsxwriter
  - python-pptx
  - pyyaml=6.0.2

  # -- PyTorch (CUDA) + ONNX Runtime (GPU via pip below)
  - pytorch=2.3
  - torchvision=0.18
  - torchtext
  - pytorch-cuda=12.1

  # -- Packages installed via pip only
  - pip:
    - transformers>=4.40.0,<4.41.0
    - optimum[onnxruntime]==1.16.2
    - onnxruntime-gpu==1.16.2
    - datasets>=2.21.0,<3.0.0
    - sentencepiece>=0.2.0
    - faker>=37.4.2
    - typer>=0.3.0,<0.10.0 # Compatible with spaCy 3.5's pinned dependency range
    - pytest
    - rich>=14.0.0
    - Pillow
    - pytesseract==0.3.10
    - easyocr
    - opencv-python
    - PyMuPDF
    - PyPDF2>=3.0,<4.0
    - reportlab
    - onnxscript>=0.5.0
