name: edgedeid
channels:
  - pytorch
  - conda-forge

dependencies:
  #── Python 環境
  - python=3.10
  - pip
  - git

  #── 科學運算 / 資料處理
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm=4.67.1
  - typing-extensions
  - python-dateutil
  - tzdata

  #── NLP ＋ 文本處理
  - spacy=3.5.*
  - python-docx
  - beautifulsoup4
  - lxml
  - jieba=0.42.1
  - openpyxl
  - xlsxwriter
  - python-pptx
  - pyyaml=6.0.2

  #── PyTorch + ONNX Runtime
  - pytorch=2.3
  - torchvision=0.18
  - torchtext            # 同步來自 pytorch channel
  - onnx=1.16.2
  - onnxruntime=1.16.2
  - onnxruntime-gpu=1.16.2

  #── 只有 pip 安裝的套件
  - pip:
    - transformers>=4.40.0,<4.41.0
    - optimum[onnxruntime]==1.16.2
    - pytesseract==0.3.10
    - easyocr
    - opencv-python
    - PyMuPDF
    - PyPDF2=3.*
    - datasets>=4.0.0
    - sentencepiece>=0.2.0
    - faker>=37.4.2
    - typer>=0.16.0
    - pytest
    - rich>=14.0.0
    - Pillow
    - reportlab
